found a problem in a pipe where 1>2 should be 1>&2

diff --git a/osiris/README b/osiris/README
--- a/osiris/README
+++ b/osiris/README
@@ -118,7 +118,7 @@
 if test "$WXHOME" = ""; then
   WXHOME=`sh findwx`
   if test "$WXHOME" = ""; then
-    echo "Cannot find WXHOME in environment" 1>2
+    echo "Cannot find WXHOME in environment" 1>&2
     exit 1
   fi
   export WXHOME
